### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [scanmem/scanmem#129]
I would like to point out that identifiers like "[`_SCANMEM_INC`](https://github.com/scanmem/scanmem/blob/6da71c90ee58f2c77e713d0dd9fec25d8d1e2a2d/scanmem.h#L1)" and "[`_VALUE_INC`](https://github.com/scanmem/scanmem/blob/174b927b5c6a20392a0ec7379a7bab07f35ddb60/value.h#L26)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by sriemer** [comment]
Hi Markus, thanks for pointing us to some issues! I'm the co-maintainer since this year. @coolwanglu maintains this software much longer. We know that the code contains a lot of legacy parts from 2007 written by @taviso and needs to be reworked and polished at some parts. We finally have to chance to do that as the most pressing bugs are fixed and version 0.15.2 has been picked up by many Linux distributions.

I'll look closer at the issues you've reported today in the evening. I'm still a bit shocked about the great increase in visitors. :+1:

Thanks for the link and the hint! Yes, reworking this makes sense.

**Comment by sriemer** [comment]
Fix committed. Solved.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/scanmem/scanmem/commit/97d55508f300c8991a7e19b5df3e5d6d23d8d973 "Deletion of a few underscores").
