### ISSUE TITLE
gui: Python 3: Save address list to file creates an empty file

### ISSUE THREAD

**Issue by mastermax1988** [scanmem/scanmem#141]
Using the save button in the gui (gameconquerer) results in creating an empty save file without addresses. Expected behaviour: the found addresses, with description and type should be saved for future needs.

**Comment by sriemer** [comment]
Thanks for reporting! Only Python 3 is affected. Also loading a file which has been saved with Python 2 doesn't work. That functionality usually doesn't work anyway any more because of position independent executables (PIE) for everything in latest Linux distributions. It also only works for static memory but games are usually coded with dynamic memory objects and C++.

**Comment by sriemer** [comment]
Address space layout randomization (ASLR) is what loads ELF libraries using position independent code (PIC) and PIE binaries to different locations in virtual memory each code execution. The support for that is only implemented into the command line tool scanmem and only for the memory scanning. The only game trainer on Linux with PIE support is [ugtrain](https://github.com/ugtrain/ugtrain).

**Comment by sriemer** [comment]
The solution is described [here](http://stackoverflow.com/questions/14031879/json-dump-big-list-containing-dict-text-datetime-and-ints-gives-typeerror-s). GameConqueror uses "wb" and "rb" to open the JSON files. That is wrong as these are text files and no binary files. So removing the "b" is the solution.

**Comment by sriemer** [comment]
The fix is committed. So closing.
