### ISSUE TITLE
Floats are always rounded down to next int - allow exact matching and ranges for them

### ISSUE THREAD

**Issue by pikajude** [scanmem/scanmem#156]
I'm assuming since floats are matched to the nearest integer, precision has bitten users in the ass before, so it would be cool if there was toggleable behavior to search the exact values of floating point numbers. I'm trying to find a specific value (say, 1.00 -> 1.35 -> 1.60) and scanmem is all but useless because so many floats are in the range 1.0-2.0.

**Comment by sriemer** [comment]
Scanmem is not meant to round floats at all currently. But I think the problem is located in `parse_uservalue_number()` and likely also other locations. The default data type is int. So it tries to match integers and floats as integers. It parses the number given as integer first and if that succeeds, it doesn't do the float parsing. So everything is rounded down to the lower integer value.
See: [parse_uservalue_number()](https://github.com/scanmem/scanmem/blob/6a5e2e86ebacd87bed132dea354433d722081abf/value.c#L153)

Introducing rounding requires quite some work. Of cause this could be handled with a further option.

Have you tried `option scan_data_type float` to scan for floats only?
That shouldn't have any rounding.

**Comment by sriemer** [comment]
I'm sure the ranges feature can help here. See PR #143.

**Comment by sriemer** [comment]
I've tested this. You're right! Even with the scan data type set to float32, it does the integer conversion. This is basically a bug. But to fix this and to be able to provide the old behavior, this depends on the ranges feature.
Thanks for reporting!

**Comment by sriemer** [comment]
Depends on #76.

**Comment by pikajude** [comment]
Thanks for the prompt response @sriemer, I'll watch that issue

**Comment by sriemer** [comment]
Ranges are implemented. I've also already seen the issue in the default handler. So implementing the rest is easy now.

**Comment by sriemer** [comment]
The issue was in the scan routines. There was even a TODO: `let user specify a float number`
Please test if latest code from the master branch fixes the issue for you as well.
