### ISSUE TITLE
[Features request] "Previous value" column, static addresses and "save to file"

### ISSUE THREAD

**Issue by davidebeatrici** [scanmem/scanmem#197]
"Previous value" column:  shows the initial scan values. The changed ones should be marked with another color.
Static memory addresses: marked with a different color. It seems like GC doesn't show the static addresses at all.
Save to file (and open): saves the table to a file and retrieves the table info from it.

All of these features are present in Cheat Engine and I think that they are useful; there are also other features missing, the pointers scan for example, but I think that the three I listed are more important :wink:

**Comment by sriemer** [comment]
GC has a "save to file" feature to save the cheat list. It can also load it but it only works for static memory values without PIE which is rare these days. GC is no real game trainer. It doesn't have the right SW arch to do sophisticated stuff like preloading.

You can see static memory with the region type "exe" and if you know that the static load address of x86_64 binaries is always 0x400000, then you can detect if the exe is a PIE or not. Use [ugtrain](https://github.com/ugtrain/ugtrain) if you need a real game trainer.

For what do you need that "previous value" stuff? Can't you remember what you've been searching for?

The pointer following stuff is of very limited use on Linux due to the high binary variation. This is why ugtrain rather hooks malloc(), free(), etc. with LD_PRELOAD to support dynamic memory. The advantage is that this is much easier to adapt.

**Comment by sriemer** [comment]
Btw.: Pointer following requires a debugger. gdb watch points could be used for that. Debugger integration would be an idea for the future. Releasing and getting `v0.16` into distributions has priority at the moment.

**Comment by sriemer** [comment]
Convince @12345ieee if you want GC features. I usually don't use GC myself. I usually only fix bugs in it and improve performance.

**Comment by davidebeatrici** [comment]
No problem, I understand that there are other priorities :wink:
About the static addresses: yes, I found out the other day that the static load address is between 0x400000 and 0x600000, the memory addresses between these two ranges are static: they remain the same even after restarting the game/program.
About the "previous value" column: it's useful to see if memory addresses change or not without doing a scan, especially in situations where the memory address switches constantly between two values.

**Comment by 12345ieee** [comment]
Convincing me is easy, just send a well written patch. :smile:
 
Jokes aside, v0.16 is already choke full of things to merge, refactor, tune up and fix ( @sriemer hasn't set a release date, but it must be done before the year, or we miss Debian stretch) and I don't even have much time any more.

If you want a new feature, either you drop a patch, or you wait for roughly Christmas before I start accepting and implementing new feature requests for the v0.17 cycle.

Also, TIL I've apparently been put in charge of the GUI.

**Comment by davidebeatrici** [comment]
I will try to do a patch, but don't expect anything: I'm not experienced in Python :wink:
Good luck with v0.16 release :smile:

**Comment by 12345ieee** [comment]
So, I am now taking new features suggestions (it's more or less Christmas time, isn't it?).

So, is there some feature that's actually missing and is still needed or I can close this?

**Comment by davidebeatrici** [comment]
All of the features are present.
