### ISSUE TITLE
[feature request] Delete multiple matches with a single `delete`

### ISSUE THREAD

**Issue by 12345ieee** [scanmem/scanmem#200]
As line 443 of `handlers.c` says: https://github.com/scanmem/scanmem/blob/master/handlers.c#L443
a standing TODO is implementing:

```
delete X Y Z K ...
```

instead of having to issue a separate `delete` command for every match id.

This feature is already implemented for the related `dregions` command.

I have in the pipeline a commit for GC (5a78f1b) that currently issues separate `delete` commands, but this is both inefficient and pretty flimsy (as higher match-id's shift up between each delete).

**Comment by bkazemi** [comment]
I was actually going to take this up soon! I will open a PR and comment back here once I have a rough draft.

**Comment by sriemer** [comment]
There is also the similar PR #146 for `dregions`. The comma and space separated list like for the `set` command would be best.

**Comment by sriemer** [comment]
Requires a further man page and help text change. So leaving this for v0.17.

**Comment by 12345ieee** [comment]
Ah, sucks we can't get it in for v0.16, but I understand the testing involved might be too much.

Could be useful to extract out the parser while you are at it, so that we can decide a complex format to support, implement it only once and then reuse it for every command that can take multiple args.

**Comment by bkazemi** [comment]
Alright, I have a rough implementation of an unsigned integer range parser and the logic to use it with `delete` [here](https://github.com/bkazemi/scanmem/tree/multi-delete). It still needs tweaking and documentation. Since it is a fairly large commit, it will need thorough testing.

**Comment by 12345ieee** [comment]
What format are you supporting?
`A,B,C..D,E,F..G` with A..G integers?

**Comment by bkazemi** [comment]
I attempted to keep the range pretty flexible. Here's the breakdown on the format:
* Numbers and ranges are separated with commas and any amount of whitespace, however, the whole expression must be in one argument (I still need to concatenate the arguments in `delete` to allow for spaces)
* The range must be a set, meaning that the user may not supply a number more than _once_. This goes for numbers implied to be included in the range, for example `1-10, 5` is invalid.
* Numbers may be supplied in any order.
* \`Open-ended\` ranges are allowed. This implies two sorts of ranges:
  * **front range:** `-10` would include all elements from the beginning of the set to 10. Since the parser can't know what the first number is, I added a new `set_prop` struct that has flags that tell whether this has been supplied by the user
  * **back range:** `10-` would include elements 10 to the last element.
* There must be at least _one_ element in the set.
I decided to implement this as an unsigned integer parser to allow for open-ended ranges. Otherwise, it would be tough to differentiate between open-ended ranges and negative numbers. It also allows for the developers to use the range functions in a more conscientious manner (it doesn't make sense to allow negative numbers in 0 indexed matches)

On the programming side, when all is said and done an array is filled with the set and the `value_set` member in the `uservalue_t` struct points to it. I declared `value_set` as `void *` to create a generic interface for ranges in case we ever would want to implement other kinds of range parsers.

**Comment by bkazemi** [comment]
Also, this parser uses the 64 bit version of the values. It is up to the caller to restrict the numbers to 32 bit or whatever.

**Comment by 12345ieee** [comment]
I know what you're going for, but `-10` is still extremely confusing.
I'd like `:10` (like python) or `..10` (like scanmem's range), the first is probably easier to code, tough this is something you and @sriemer should decide.

**Comment by bkazemi** [comment]
I agree that it isn't really intuitive for the user. I'll go ahead and switch to `..` delimiters, and wait on @sriemer about the python style.

**Comment by 12345ieee** [comment]
Any is fine for me.
So this: `        A,      B..C,D.., ..F,               ` is the full supported format.
What do you mean with "he whole expression must be in one argument (I still need to concatenate the arguments in delete to allow for spaces)"?

**Comment by bkazemi** [comment]
I meant that the whole range still needs to be in `argv[1]`. When there are spaces in the range it is interpreted as multiple arguments.

**Comment by 12345ieee** [comment]
Aaaah, `A  ..  B` is bad, thanks.

**Comment by bkazemi** [comment]
Also another note: This range implementation handles #187 properly.

**Comment by 12345ieee** [comment]
@bkazemi , gcc6 spits out this warning:

```
value.c: In function ‘parse_uservalue_uintset’:
value.c:347:35: warning: ‘last_num’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 if ((arr_szfilled += (tokval.uint64_value - last_num)) > arr_maxsz)
                     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by 12345ieee** [comment]
You also suffer from the id-shifting problem, look:

* scan, get N matches
* run `delete N-2,N-1` (which are both good match ids)

Result:
* Only match N-2 is deleted
* `warn: you specified a non-existant match ``N-1``.`

That's because (I guess), you remove ids sequentially, but they shift up as you do, so at the end the numbers are different than the ones you started with.

In GC I worked around this by sorting the list and deleting the highest match ids first, whatever trick you use, you have to handle this correctly.

**Comment by bkazemi** [comment]
That warning is a false positive, that statement is protected by a check for `got_num == false` in which case the statement is never reached.

Ah, I hadn't tested this code against real match deletions. That seems a bit tricky for developers, I think ID's should be shifted manually by a function call to avoid this issue.

**Comment by 12345ieee** [comment]
IMHO, the front-end dev should be able to call `delete A,B` and get both correctly deleted, regardless of the intermediate states the program gets to, but he never sees.

You, as a back-end dev, can either go for the cheap biggest-first sorted array approach or rework the id-shifting in implementing this.

**Comment by bkazemi** [comment]
Agreed. For now, I'll just do top down deletion. I'll look at the shifting code later and see what's feasible.

**Comment by 12345ieee** [comment]
@bkazemi , how is this one going?

It's something I'd really like to have for v0.17, if you need any kind of help, just ask.

**Comment by bkazemi** [comment]
I believe this one is almost finished; I just need to add some more code in `handlers.c`. I'll put this at the top of my TODO list.

**Comment by bkazemi** [comment]
Alright, I have everything implemented. It is still without the final touches. There are some subtle bits in the code, I will be sure to add comments later. Having parsers like this should make input sanitation more robust.

**Comment by 12345ieee** [comment]
Can you make a PR when you have a semi-final version? It's easier to review/discuss that way.

**Comment by 12345ieee** [comment]
#266 has been merged, so this has been implemented.
Closing.
