### ISSUE TITLE
What do you think of CE-server?

### ISSUE THREAD

**Issue by korcankaraokcu** [scanmem/scanmem#203]
Apparently, Cheat Engine has a server called "ce-server" which allows CE to attach native linux processes and perform scanning&basic debugging. By time, CE will work on Linux like it works on Windows eventually. So, is this a duplication of effort? Are we struggling for nothing? This ce-server thing completely screwed my morale up

**Comment by 12345ieee** [comment]
> By time, CE will work on Linux like it works on Windows eventually

Considering the sheer difficulty I had to just find it on google, 'eventually' might mean 'next century'.

Do you know what it actually does?

**Comment by korcankaraokcu** [comment]
CE-server lets a CE process running in windows environment(for instance WINE) to target linux processes by communicating via sockets. It converts CE API to linux. See api.c in [this page](https://github.com/cheat-engine/cheat-engine/tree/master/Cheat%20Engine/ceserver)

**Comment by 12345ieee** [comment]
The development seems pretty dead looking at commits timestamps.
Well, first step would be to contact the other project maintainer and ask what's going on.

I don't think this is very relevant to scanmem in itself, you'd better open an issue at the CE repo and @mention people that may be interested (like myself).

**Comment by sriemer** [comment]
The CE-server for Linux is dead and very limited in functionality. CE doesn't work on Wine and it is too cumbersome to run a separate Windows machine just for the front-end. Things work much differently on Linux. So it makes sense to have different tools on Linux.
That Lazarus stuff is completely crap for Linux as nothing else is using that. Pascal is also a dead programming language.
IMHO pointer following is also stupid on Linux if it can be avoided because of the high variation of binaries and the frequency of game updates. So automatic adaptation of configs/cheat lists is quite mandatory.
I don't miss CE on Linux as I have `scanmem` for the search and `ugtrain` with its unique memory hacking library preloading as a really useful universal game trainer. Ugtrain also has simple pointer following support now if one really needs that.
