### ISSUE TITLE
What is game_conqueror's equivalent to Cheat Engine's "4 byte"?

### ISSUE THREAD

**Issue by hub2git** [scanmem/scanmem#232]
https://konghack.com/topic/10585-burrito_bison_launcha_libre/2?p=102778 advises Cheat Engine users to search for "4 byte". What is the equivalent in Game Conqueror?

**Comment by sriemer** [comment]
`int32`. But the default `int` is also fine.

**Comment by sriemer** [comment]
If you have no idea if the value could be a float as well, then use `number` and a small range like `200..201` if 200 is visible in a game.

**Comment by sriemer** [comment]
Integers: Warzone 2100, Cube 2: Sauerbraten, Supertux 2, Alien Arena, ...
Floats: Chromium B.S.U., Dune Legacy, ...

There are more games using integers but some use floats instead.

**Comment by korcankaraokcu** [comment]
New flash games tend to use variables in double type. For instance, berzerkland was using double type for all protected variables in their games. It'd kick you out of the game if the variable was changed.

Also old games like Soldat usually try to optimize space. The max count for bullets were 100 so it used byte instead of integer for storing.

So, you should try every type regardless of the thing you are searching for if int32 doesn't work

**Comment by sriemer** [comment]
This is exactly what `number` is good for. It checks all ints and all float types.

**Comment by 12345ieee** [comment]
I cheated in that game like 3 days ago, there is a post of mine 2 posts over the linked konghack thread.

Can confirm that game uses int32.

@korcankaraokcu : Flash is going away, the game in question is a Unity OpenGL build, like most new browser-bound games.
