### ISSUE TITLE
Filter matches by memory address? Or how to handle ASLR for static memory?

### ISSUE THREAD

**Issue by bobbyhopere** [scanmem/scanmem#240]
Add support to search by memory address.

ASLR will change the addresses each time the process is started but the target addresses always end with the same byte. This is true for NES, SNES, Sega, etc. emulations. This would make searching faster when we already have a long list of addresses.
Example. The first 3 bytes may change but the last one is always the same.
0x??????AB

**Comment by sriemer** [comment]
Did you check the bytearray search? It provides the possibility to search for `?? ?? ?? AB` in memory.

Personally I rather use the match offset which is provided by scanmem and determine the load address of that memory region at every game start by looking at /proc/maps.

Do you know that the Linux game trainer [ugtrain](https://github.com/ugtrain/ugtrain) is coming with PIE support for static and dynamic memory?

The magic is stored in [aslr.cpp](https://github.com/ugtrain/ugtrain/blob/master/src/aslr.cpp#L235).

**Comment by sriemer** [comment]
Searching again and again for the same static memory value at every game start of cause doesn't make much sense and is tedious. This is why game trainers with ASLR support have been invented - I only know of my own one on Linux: ugtrain.

If more people are voting for this, then I'll think about implementing PIE support for GameConqueror. But that will be limited to static memory and the GC save file format would change.

The calculation `load address + match offset = current static memory address` can be also done manually. Then you can use the scanmem `write` command or the GC option to add a cheat manually.

**Comment by sriemer** [comment]
x86_64 non-PIE example for simplicity:
````
0> lregions
[ 0]       62f000,  147456 bytes,   exe,       400000, rw-, /usr/bin/chromium-bsu
...
````

The .data region of the ELF executable chromium-bsu starts here at 0x62f000. Non-PIE executables on x86_64 are always loaded to 0x400000 as their .code region is starting there.

Typical ELF regions are .code, .rodata, .data and .bss. As .code and .rodata are not marked r/w, scanmem removes these from the regions list.

Example match here:
````
1> list
[ 0]       62fbb4,  0 +       22fbb4,   exe, C h r o, [string]
````
`0 +       22fbb4` means that 0x62fbb4 = the load address of region 0 + match offset 0x22fbb4.

**Comment by sriemer** [comment]
Does this answer your question?

**Comment by bobbyhopere** [comment]
Yes, ok, there is a workaround already available.

**Comment by sriemer** [comment]
The advantage of using the .text load address instead of the .data start address is that you get the same data offset as used within the PIE (check the disassembly with `objdump -D`). So in some cases you can search for that memory offset in the code and don't have to run `gdb` with a watchpoint set to that memory address.

PIE works by using the instruction pointer %rip as the base and then adding an offset for the variable. In the comment you can see the offset with .text start as the base. GCC also compiles non-PIE this way.

E.g. `warzone2100` stores the player 0 power value in an u64 array. Values are stored as pseudo floats u32.u32. So `scanmem` finds it as i32.

Non-PIE `warzone2100` power of player 0 (campaign starts with 1300):
````
1> list
[ 0]       dec964,  1 +       9ec964,   exe, 1200, [I32 I16 ]
````

Load of the u64 `asPower` array address 0xdec960 into %r9 within the `objdump -D` output:
````
576602:       4c 8d 0d 57 63 87 00    lea    0x876357(%rip),%r9        # dec960 <_ZL7asPower>
````

With PIE, you would see something like 0x9ec960 here.

Question answered. So closing for now. Thanks!
