### ISSUE TITLE
gui: Should use Python 3 in shebang line by default

### ISSUE THREAD

**Issue by sriemer** [scanmem/scanmem#300]
No distribution allows to package Python tools which support Python 3 still as Python 2. So the shebang line in `GameConqueror.py` should be changed accordingly s/python/python3/.

I have a patch for this and this is already included in Debian packaging (#288).

@12345ieee: Are you fine with the change?

**Comment by 12345ieee** [comment]
I'm not sure I understand the idea behind it, @sriemer .

AFAIK, python is now in a "transition phase", with most distros shipping both python's and some having py2 as default, some py3.

GC was maintained compatible with both python versions (it was not easy, back in 0.16) and the shebang set to `python`, so that we wouldn't choose a version for the user, but we'd work with whatever the distro provided by default.

Now that py3 is getting more widespread, we could drop py2 support altogether and change the shebang to `py3`, but just changing the shebang offers none of the benefit (the source still has the py2 support code) and all of the problems (GC won't work if only py2 is installed).

That being said, I'll be very happy when we'll transition to py3 only, removing the py2 support, but until we decide to do that, I'd not change the shebang upstream.

If I missed your point, do tell.

**Comment by sriemer** [comment]
Okay, let's do the transition then for v0.18 then.
