### ISSUE TITLE
Can scanmem do a read-only search that won't be detected by the target process?

### ISSUE THREAD

**Issue by krisives** [scanmem/scanmem#320]
Currently I scan a program that likely has code to detect modification of the program memory for anti-cheat purposes. I'm trying to reverse engineer the memory map / layout of the process and want to avoid making any changes. When I run `scanmem` and give it a known value to find it begins searching the memory map and eventually encounters an area of memory at which point the process detects unwanted changes happening and exits.

I am running `scanmem` as root and the target process is running as non-root.

Does `scanmem` make any changes to the memory layout otherwise how is the program in question detecting the scan?

**Comment by 12345ieee** [comment]
There are a variety of ways this application could detect memory scanning.

Assuming you are on a target that supports `/proc/<pid>/mem`, `scanmem` works by sending the `PTRACE_ATTACH` signal to the process, waiting for it to work, then reading in memory regions from `/proc/<pid>/mem`.

At no point `scanmem` modifies the program's memory during a scan (you can easily modify it later, but that's not the issue here).

Given that you say the program terminates while `scanmem` is scanning, but in that timeframe the traced process is `STOP`ped, something strange is happening, are you sure that you aren't seeing another thread report, which might be monitoring `/proc/<pid>/`?

Also, if you believe this is tied to a specific region, you can use the `dregion` command to scan only a subset and isolate the culprit.

**Comment by sriemer** [comment]
It is also possible to detect `ptrace()` by calling `ptrace(PTRACE_TRACEME, ...)`. The anti-anti-ptrace is to use LD_PRELOAD and to override ptrace() to tell the tracee that there is nothing tracing it although it is completely compromised. :smiling_imp:

**Comment by krisives** [comment]
@sriemer I looked at the Linux code for the procfs `/proc/pid/mem` and from what I can tell it doesn't send any signals if simply reading memory without using the ptrace API, is this correct? I know the target program I was scanning memory for didn't seem to trigger anti-debugging code when I simply read memory, which leads me to believe no signal was sent.

**Comment by 12345ieee** [comment]
I had done some tests on this topic, and on my system (debian unstable) I can perform readonly scans if I replace the `PTRACE_ATTACH/DETACH` calls with matching `kill(SIGSTOP/CONT)`, but you can't modify memory that way, just read.

If you want `scanmem` to do that, the relevant functions are `sm_attach()` & `sm_detach()` in `ptrace.c`, replace `ptrace(things)` with `kill(things)`.

Using `PTRACE_ATTACH` unconditionally is a remnant of when we did everything with `ptrace()`, I might think about a compile time switch to use `kill()` for readonly scans.

**Comment by sriemer** [comment]
Yep, only `PTRACE_ATTACH` is detected by the tracee. I've provided the tricks how to bypass this if r/w is required. IMHO it doesn't make sense for us to support this case with a compile-time switch. At some point you'll end up requiring a working r/w method. A custom modification is the way to go for the read-only scan.
