### ISSUE TITLE
Feature Request named or saved snapshots

### ISSUE THREAD

**Issue by asdf23** [scanmem/scanmem#340]
I'd like to take a snapshot associate it with a name (or file) then refine the list, then do a comparison to the snapshot. 

So...
>Megaman has full life
Run command: snapshot "Full_Life"
>Megaman gets hit
Run command: <
>Megaman dies and a new game starts
Run command: =snapshot "Full_Life"

If the snapshot contains memory regions that the current list does not, then ignore.

Also if I could get the snapshot exported to a file I think I could use a diff tool to help understand what is going on.

**Comment by 12345ieee** [comment]
See https://github.com/scanmem/scanmem/issues/341#issuecomment-509016835

**Comment by sriemer** [comment]
Sorry, but this is stupid due to **dynamic memory** on the heap which is the concept behind **object-oriented programming**. You might want to look into [ugtrain](https://github.com/ugtrain/ugtrain) and its memory object dumping feature. There I use `vbindiff` to find further interesting values within the same memory class.

Megaman dies means `delete megaman;`, `free(megaman);`, or in other words: The memory is freed and when the next Megaman object is created on the heap, then it would be a *miracle* if it would be allocated to the same memory location.

**Comment by sriemer** [comment]
Feature request rejected. Sorry. Dump only relevant memory.
