### ISSUE TITLE
ptrace don't get attached

### ISSUE THREAD

**Issue by Ali-Khazaee** [scanmem/scanmem#367]
I did try to edit game value but scanmem cannot attach it because the game have traced itself is there anyway to handle this in scanmem ?

**Comment by sriemer** [comment]
How exactly does it do that? `ptrace(PTRACE_TRACEME, ...)`?
That is the usual anti-ptrace method. The counter measure is using `LD_PRELOAD` to preload a library which overwrites `ptrace()` and fakes that the `ptrace()` call worked.

**Comment by Ali-Khazaee** [comment]
I'm talking about Android, LD_PRELOAD do not works on Android API > 21

**Comment by Ali-Khazaee** [comment]
i did test LD_RELOAD like this:

first i made a shared librarythat rewrite ptrace function
then i set export LDPRELOAD=PathToSharedLibrary
then start game, then use scanmem

Is this correct ? if yes do not works on Android > 21

**Comment by sriemer** [comment]
The other method is just using `ptrace()` to attach before the `main` function by starting the game and to load the library inside the game process with `dlopen()`. This method is pretty complex and arch specific. So it is easier if `gdb` is available with its `call` command. E.g. PINCE does it here: https://github.com/korcankaraokcu/PINCE/blob/3ad170591bbc4313c59a9ddcc80b3c281e5dac20/libPINCE/GDB_Engine.py#L678
In the past I've also modified the tool `patchelf` to work on a real GNU/Linux smartphone based on ARM (Nokia N9) so that the dynamic loader is instructed to load the library at every execution.

So executing the game with early ptrace() attaching with ptrace() based library injection or patching the executable to tell the dynamic loaded to load a further library are the options here.

**Comment by sriemer** [comment]
From time to time the smartphone checked executable hashes. So it detected the modification now and then. Just overwriting again was my workaround for that as I didn't want to search for the hashing functionality to make it accept the modification permanently. Also an installer hack was required for using `ptrace()` at all.
