### ISSUE TITLE
Building GameConqueror on OpenSUSE TW: No module named gi?

### ISSUE THREAD

**Issue by alexholox** [scanmem/scanmem#405]
I run from the command line on opeSUSE Tumbleweed and this is what I get:

```
Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 35, in <module>
    import gi
ImportError: No module named gi

```

I installed every pre-requisie except python which I forgot. Then, I ran it and noticed I lacked python so installed it. Now I have everything and can't open GameConqueror because this appears and in usr/lib64 I don't see the app. Please help! What to do?

**Comment by sriemer** [comment]
I guess this question is answered. So closing.

**Comment by DHLF** [comment]
GERMAN:

gamconqueror FEHLER: gi blabla
falsche Version von gi: gesucht wird PYTHON2-gi gibts nicht
mehr(bullseye) (python-gi-dev ist 3.x!)
Aufruf der DEV version von gameconqueror mit: python3 gameconqueror
Fehlermeldungen in der bash ignorieren..
bzw. /usr/bin gameconqueror LESEN und dadurch
/usr/share/gameconqueror.py erste Zeile ändern in(also bei python eine 3
anhängen!!(via sudo!):
#!/usr/bin/env python3


Translation try in english:


This may NOT be the adequat solution but I ran into the very same
problem: module gi not found (or something like this)

ONE way ist to launch gameconqueror with the command "python3
gameconqueror"

(ignore the error messages in the console, but this way it will launched
with the proper version (python3!)

  OR

edit

/usr/share/gameconqueror.py

and change first line (instead of just "python" set it to "python3")


I dont know my password to access the mailing list myself so please if
this works for you tell it to the group so there is a solution

regads,
