### ISSUE TITLE
running build_for_android.sh generates an x86_64 binary

### ISSUE THREAD

**Issue by hellidox** [scanmem/scanmem#415]
no idea what the hell is going on, i made an arm64 standalone ndk and everything

**Comment by 12345ieee** [comment]
Even the stuff in `/home/atrius/git/ndk/sysroot/usr/bin/scanmem` is x86_64?

**Comment by kqee** [comment]
hello! I'd like to reopen this issue, because I am currently facing the same problem, I've been sitting in one position for hours to fix but to no avail.

I have followed the instructions given in `./build_for_android.sh --help`, I downloaded NDK standalone and created the toolchain as below:
```sh
./build/tools/make_standalone_toolchain.py --arch arm64 --install-dir ../ndk-toolchain --force --verbose
```
I exported the required env. vars:
```
export NDK_STANDALONE_TOOLCHAIN=$(realpath ../ndk-toolchain)
export HOST=arm64-linux-androideabi
```
then I ran the script:
```sh
./build_for_android.sh
```
below is the log; output when build script is launched.
[log.txt](https://github.com/scanmem/scanmem/files/12599092/log.txt)
