### ISSUE TITLE
Computer architecture, or rather, size of the word processed by the processor (64 bits or 32 bits).

### ISSUE THREAD

**Issue by Forg0ttenUser** [scanmem/scanmem#443]
# 32-bit, please.
I would like to know if there is a 32-bit version available, as I need the supported "word" to be of this size, since in one game (Shadow of the Colossus) I can't find it. The problem is that I can't access a certain memory address with the 64-bit version. Thanks in advance.

**Comment by sriemer** [comment]
32-bit are supported. You can build scanmem yourself for 32-bit systems. Also searching in 32-bit words is supported just set the scan data type to `int32`. It is even in the `help option` help text: `option scan_data_type int32`.
We will not support hacking your commercial game.

So does this answer your question?

If not, then please provide a proper (minimal) test case for issues. Use a very simple C program just initializing and modifying some data on command and sleeping in a loop otherwise.

Closing this issue for now. Will reopen once proper information is provided. Thanks.

**Comment by Forg0ttenUser** [comment]
*Thank you for your reply. I have already managed to solve the problem. Thank you very much for your time.*
