### ISSUE TITLE
Big-Endian Variable Support on Little-Endian Systems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [scanmem/scanmem#70]
```
What steps will reproduce the problem?

1. Open GameConqueror.
2. Attach to a process which uses endianness different from the system default.
3. Try to search for a variable which is more than 1 byte.

What is the expected output? What do you see instead?

Expected: I should be able to choose the endianness in the GameConqueror GUI, 
so that the search will succeed.  Actual: endianness is fixed at the system 
default, so the search doesn't get the result I want.

What version of the product are you using? On what operating system?

0.13-1 on Linux Mint 15 x64.

Please provide any additional information below.

I'm trying to use GameConqueror to debug GameCube and Wii games using Dolphin.  
The GameCube and Wii use PowerPC, which is big-endian, while x64 Linux is 
little-endian.  So searches fail due to endianness differences.  Is there a way 
that searches for big-endian variables could be implemented on little-endian 
systems?  Thanks.
```

Original issue reported on code.google.com by `biolizar...@gmail.com` on 16 Feb 2014 at 2:30

**Comment by coolwanglu** [comment]
It should has been fixed via the PR.

**Comment by JeremyRand** [comment]
Hi, thanks for getting this dealt with.  Sorry I didn't notice earlier, the Google Code exporter broke my notifications.  BountySource is still pointing to the Google Code issue, and therefore hasn't noticed that the bounty is claimable... I'll email their tech support in a few days and ask them to mark it as complete so that the bounty can be awarded.  Cheers.

**Comment by coolwanglu** [comment]
@JeremyRand I just checked the bountysource url, seems that the old issue on google code is automatically redirect here. (good job google code exporter!)
And just a note, this issue was fixed by https://github.com/coolwanglu/scanmem_/pull/29

**Comment by sriemer** [comment]
... and it broke the build so that I had to develop a really working endienness detection in PR #89,...

**Comment by JeremyRand** [comment]
Just talked to BountySource; the bounty should now be claimable at https://www.bountysource.com/issues/10346802-big-endian-variable-support-on-little-endian-systems .  Sorry about the delay.

**Comment by sriemer** [comment]
@hraban should claim it or donate it to the scanmem project as he didn't care for his code any more once it caused trouble.

**Comment by hraban** [comment]
hey guys, thanks for getting this sorted out!
Hi guys,

I'm generally not a fan of putting oil on the fire, or participating in discussions about me. However, I'd like to say at least something in my defense regarding breaking the build: that's completely true, I broke the build for hybrid archs (like ARM). The reason I didn't step in when this was addressed wasn't so much a lack of care, as a combination of:

1. The solution was to choose between switching to runtime init, or introducing autotools into the build process. Both with their pros and cons, in the end an inherently subjective choice better left to the maintainer.
2. The environment around the bug had been taking a turn that I thought would be better for me not to participate in anymore. A judgement call, and I now regret not sending Lu Wang an e-mail about it to explain my pov.

Anyway, I hope this at least explains, if not excuses, my radio silence after the issue of hybrid archs had been brought up.

Lu Wang, would you mind if I claimed the bounty?

Sebastian, since you went through the trouble of fixing the mess I introduced (thanks!), do you want to share it?

Cheers,

Hraban

**Comment by sriemer** [comment]
@hraban You can have it. Thanks for explaining!

Better testing would be nice next time as it also broke the build for powerpc which is more or less the reference arch for big-endian systems. Valgrind also shows a performance problem with your `fix_endianness()` function. So we'll have to fix that later on as well. Placing a function in the hot scan path definitely needs better testing. IMHO this whole stuff can be inlined instead of wasting precious CPU cycles by calling real functions.

**Comment by hraban** [comment]
Hi Sebastian. Do you know which functions are not inlined? I understand the top level function is not inlined in the caller code but if the smaller sub functions are not inlined either that could be a problem. Although, hopefully, fixable by finding the right compiler flags?

**Comment by sriemer** [comment]
If you compile a separate c file and therefore an object file, then the public function can't be inlined and that's exactly the problem here. Just look at the disassembly. All functions regarding this should be put as inline functions into the header file.

**Comment by 12345ieee** [comment]
I have a question here, I @-mention relevant people: @sriemer , @hraban , @coolwanglu .

Why is the endianness swap implemented on the data in memory, instead of on the user-given data?

In `checkmatches()` and `searchregions()` the function is called in the hot path, it was inlined in e536fc90ce1b67149d98db81da31d4dd040ddc60 , but is there some reason it cannot be called just once on the user-given data (possibly twice), instead of one time per byte (aka ~100M times)?

**Comment by hraban** [comment]
Hi @12345ieee !! To be honest this is so long ago, I don't remember the particular decisions I made back then. If it's not clear from the code there should have been a comment, so mea culpa. Moreover, I was never intimately familiar with the codebase. I wanted to fix this issue, so I delved in, tried to understand it, tried to imagine what the best place would be, and implemented a fix. It's very possible I missed a (much) better alternative method to fix it.

Perhaps the reviewers from back then know more. Chances are it was just sub-optimal.

**Comment by sriemer** [comment]
As long as bytes don't have to be swapped there is not much of a performance penalty. As I don't need that as all my systems are LE, I don't care for performance penalties when bytes have to be swapped.

**Comment by 12345ieee** [comment]
Yes, indeed, you can just see a penalty of ~10% on the LE vs BE case.

In any case, moving away the byte swap is not feasible in general, not without huge complications on the `BIGGER/LOWER_THAN` scans, so now that I've understood the code I'd say there is nothing to do.

Thanks for the input guys.
